services:
  ecoleta-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecoleta-server
    ports:
      - "3333:3333"
    restart: unless-stopped

  ecoleta-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ecoleta-web
    ports:
      - "3000:80"
    depends_on:
      - ecoleta-server
    restart: unless-stopped


